# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Titipat
# email: me@holykyun.com
description: บล็อกน้อยๆของหนุ่มวิศวะคอมติดดอย มช
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://holykyun.com" # the base hostname & protocol for your site
twitter_username: holykyun
github_username:  titipat

# Build settings
markdown: kramdown

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page/:num"
