title: Titipat's blog
description: บล็อกน้อยๆของหนุ่มวิศวะคอมติดดอย มช
url: "https://titipat.github.io"
twitter_username: holykyun
github_username: titipat
encoding: UTF-8

markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments

# Pagination
paginate: 5
paginate_path: "/page/:num"
