title: Titipat's blog
description: บล็อกน้อยๆของหนุ่มวิศวะคอมติดดอย มช
url: "https://titipat.github.io"
twitter_username: holykyun
github_username: titipat
encoding: UTF-8

highlighter: redcarpet

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page/:num"
