title: Titipat's blog
description: บล็อกน้อยๆของหนุ่มวิศวะคอมติดดอย มช
url: "https://titipat.github.io"
twitter_username: holykyun
github_username: titipat

markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

plugins_dir: 
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-default-layout
  - kramdown
  - rouge
paginate: 5
paginate_path: "/page/:num"

sass:
  style: compressed

timezone: Asia/Bangkok
